apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: web
  namespace: default
spec:
  containers:
  - name: echo
    imagePullPolicy: IfNotPresent
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
